networks:
  wengchat-network:

services:
  wengchat:
    image: na2cucl4/wengchat:latest
    container_name: wengchat
    restart: always
    ports:
      - 127.0.0.1:3001:3000
    networks:
      - wengchat-network
    environment:
      BASE_URL: ${BASE_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      CODE: ${CODE}
      ENABLE_MCP: ${ENABLE_MCP:-false}
      CUSTOM_MODELS: ${CUSTOM_MODELS}
      DEFAULT_MODEL: ${DEFAULT_MODEL}
      FILE_READING_SERVER: http://nextchat-readfile:8000
      HIDE_USER_API_KEY: 1
      MINERU_SERVER: http://mineru-api:8000

  nextchat-readfile:
    image: na2cucl4/nextchat-readfile:latest
    container_name: nextchat-readfile
    restart: always
    profiles:
      - readfile
    expose:
      - 8000
    networks:
      - wengchat-network
    environment:
      BASE_URL: ${BASE_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DOCINTEL_ENDPOINT: ${DOCINTEL_ENDPOINT}
      DOCINTEL_API_KEY: ${DOCINTEL_API_KEY}
      DOCINTEL_MODEL: ${DOCINTEL_MODEL}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000 || exit 1"]

  mineru-api:
    image: mineru:latest
    container_name: mineru-api
    restart: always
    profiles:
      - mineru
    expose:
      - 8000
    networks:
      - wengchat-network
    environment:
      MINERU_MODEL_SOURCE: local
    entrypoint: mineru-api
    command:
      --host 0.0.0.0
      --port 8000
      --allow-public-http-client
      # --gpu-memory-utilization 0.5
    ulimits:
      memlock: -1
      stack: 67108864
    ipc: host
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
